# Generated by Django 4.2.6 on 2023-10-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SharedWith',
            fields=[
                ('share_id', models.IntegerField(primary_key=True, serialize=False)),
                ('locked', models.BooleanField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackgtx.image')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackgtx.user')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackgtx.user'),
        ),
        migrations.AddField(
            model_name='image',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackgtx.music'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friendship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='hackgtx.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_id', to='hackgtx.user')),
            ],
        ),
    ]
